/*
 * This file was automatically generated by EvoSuite
 * Tue Nov 11 21:06:44 GMT 2025
 */

package org.apache.commons.cli.help;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.PriorityQueue;
import java.util.ServiceLoader;
import java.util.SortedSet;
import java.util.TreeSet;
import java.util.Vector;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.example.WeirdOptionFormat;
import org.apache.commons.cli.help.TableDefinition;
import org.apache.commons.cli.help.TextStyle;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TableDefinition_ESTest extends TableDefinition_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>();
      ArrayList<String> arrayList0 = new ArrayList<String>();
      TableDefinition tableDefinition0 = TableDefinition.from("", linkedList0, arrayList0, (Iterable<List<String>>) null);
      Iterable<List<String>> iterable0 = tableDefinition0.rows();
      assertNull(iterable0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TreeSet<List<String>> treeSet0 = new TreeSet<List<String>>();
      PriorityQueue<List<String>> priorityQueue0 = new PriorityQueue<List<String>>((SortedSet<? extends List<String>>) treeSet0);
      TableDefinition tableDefinition0 = TableDefinition.from("RegexFileFilter [pattern=", (List<TextStyle>) null, (List<String>) null, priorityQueue0);
      List<String> list0 = tableDefinition0.headers();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>();
      ArrayList<String> arrayList0 = new ArrayList<String>();
      TableDefinition tableDefinition0 = TableDefinition.from("", linkedList0, arrayList0, (Iterable<List<String>>) null);
      List<String> list0 = tableDefinition0.headers();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ArrayList<TextStyle> arrayList0 = new ArrayList<TextStyle>();
      Vector<String> vector0 = new Vector<String>();
      ArrayDeque<List<String>> arrayDeque0 = new ArrayDeque<List<String>>();
      TableDefinition tableDefinition0 = TableDefinition.from((String) null, arrayList0, vector0, arrayDeque0);
      vector0.add("org.apache.commons.cli.help.TableDefinition$1");
      List<String> list0 = tableDefinition0.headers();
      assertTrue(list0.contains("org.apache.commons.cli.help.TableDefinition$1"));
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      LinkedHashSet<List<String>> linkedHashSet0 = new LinkedHashSet<List<String>>(1038);
      TableDefinition tableDefinition0 = TableDefinition.from("yNs1iK5", (List<TextStyle>) null, linkedList0, linkedHashSet0);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ArrayList<TextStyle> arrayList0 = new ArrayList<TextStyle>();
      Vector<String> vector0 = new Vector<String>();
      ArrayDeque<List<String>> arrayDeque0 = new ArrayDeque<List<String>>();
      TableDefinition tableDefinition0 = TableDefinition.from((String) null, arrayList0, vector0, arrayDeque0);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      LinkedHashSet<List<String>> linkedHashSet0 = new LinkedHashSet<List<String>>(1038);
      TableDefinition tableDefinition0 = TableDefinition.from("yNs1iK5", (List<TextStyle>) null, linkedList0, linkedHashSet0);
      String string0 = tableDefinition0.caption();
      assertEquals("yNs1iK5", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ArrayList<TextStyle> arrayList0 = new ArrayList<TextStyle>();
      Vector<String> vector0 = new Vector<String>();
      ArrayDeque<List<String>> arrayDeque0 = new ArrayDeque<List<String>>();
      TableDefinition tableDefinition0 = TableDefinition.from((String) null, arrayList0, vector0, arrayDeque0);
      String string0 = tableDefinition0.caption();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      Class<Option> class0 = Option.class;
      ServiceLoader<Option> serviceLoader0 = ServiceLoader.load(class0);
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) serviceLoader0);
      Iterable<List<String>> iterable0 = tableDefinition0.rows();
      assertNotNull(iterable0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      Class<Option> class0 = Option.class;
      ServiceLoader<Option> serviceLoader0 = ServiceLoader.load(class0);
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) serviceLoader0);
      String string0 = tableDefinition0.caption();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      Class<Option> class0 = Option.class;
      ServiceLoader<Option> serviceLoader0 = ServiceLoader.load(class0);
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) serviceLoader0);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      assertFalse(list0.isEmpty());
  }
}
