/*
 * This file was automatically generated by EvoSuite
 * Tue Nov 11 20:51:07 GMT 2025
 */

package org.apache.commons.cli.help;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Locale;
import java.util.PriorityQueue;
import java.util.ServiceLoader;
import java.util.Set;
import java.util.Stack;
import java.util.TreeSet;
import java.util.function.Function;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.OptionGroup;
import org.apache.commons.cli.Options;
import org.apache.commons.cli.example.WeirdOptionFormat;
import org.apache.commons.cli.help.HelpAppendable;
import org.apache.commons.cli.help.HelpFormatter;
import org.apache.commons.cli.help.OptionFormatter;
import org.apache.commons.cli.help.TableDefinition;
import org.apache.commons.cli.help.TextStyle;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AbstractHelpFormatter_ESTest extends AbstractHelpFormatter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      helpFormatter0.setSyntaxPrefix("Q8@sV");
      HashSet<Option> hashSet0 = new HashSet<Option>();
      helpFormatter0.printHelp("4BL+Ps)6|~K", "org.apache.commons.text.StrLookup", (Iterable<Option>) hashSet0, "File must not be null or blank", false);
      assertEquals("Q8@sV", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      PriorityQueue<Option> priorityQueue0 = new PriorityQueue<Option>();
      helpFormatter0.setSyntaxPrefix("Value must not be empty");
      helpFormatter0.printHelp("Value must not be empty", "P(3UfV5e/KU)1C|=wB", (Iterable<Option>) priorityQueue0, "P(3UfV5e/KU)1C|=wB", true);
      assertEquals("Value must not be empty", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      PriorityQueue<Option> priorityQueue0 = new PriorityQueue<Option>(helpFormatter0.DEFAULT_COMPARATOR);
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) priorityQueue0);
      helpFormatter0.printOptions(tableDefinition0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      Options options1 = options0.addOption((String) null, "huR", true, "The option '%s' was specified but an option from this group has already been selected: '%s'");
      String string0 = helpFormatter0.toSyntaxOptions(options1);
      assertEquals("[--huR <arg>]", string0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      OptionGroup optionGroup0 = new OptionGroup();
      Option option0 = new Option("yj", "yj", false, "lC0");
      OptionGroup optionGroup1 = optionGroup0.addOption(option0);
      String string0 = helpFormatter0.toSyntaxOptions(optionGroup1);
      assertEquals("[-yj]", string0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      Option option0 = new Option("hU", "");
      OptionGroup optionGroup1 = optionGroup0.addOption(option0);
      Collection<Option> collection0 = optionGroup1.getOptions();
      String string0 = helpFormatter0.toSyntaxOptions((Iterable<Option>) collection0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
      assertEquals("[-hU]", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      Options options1 = options0.addOption((String) null, "huR", true, "The option '%s' was specified but an option from this group has already been selected: '%s'");
      helpFormatter0.sort(options1);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      ArrayList<Option> arrayList0 = new ArrayList<Option>();
      Option option0 = new Option("x", "org.apache.commons.cli.help.AbstractHelpFormatter", false, "z8|l](O^AY?FpKC&+p1");
      arrayList0.add(option0);
      helpFormatter0.sort((Iterable<Option>) arrayList0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      helpFormatter0.setSyntaxPrefix((String) null);
      String string0 = helpFormatter0.getSyntaxPrefix();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setOptionGroupSeparator((String) null);
      HelpFormatter helpFormatter0 = helpFormatter_Builder1.get();
      String string0 = helpFormatter0.getOptionGroupSeparator();
      assertEquals("", string0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      helpFormatter0.getOptionFormatBuilder();
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      // Undeclared exception!
      try { 
        helpFormatter0.toSyntaxOptions((Options) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      // Undeclared exception!
      try { 
        helpFormatter0.toSyntaxOptions((OptionGroup) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      LinkedList<Option> linkedList0 = new LinkedList<Option>();
      linkedList0.add((Option) null);
      // Undeclared exception!
      try { 
        helpFormatter0.toSyntaxOptions((Iterable<Option>) linkedList0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.OptionFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      ArrayList<Option> arrayList0 = new ArrayList<Option>();
      arrayList0.add((Option) null);
      arrayList0.add((Option) null);
      LinkedList<Option> linkedList0 = new LinkedList<Option>(arrayList0);
      // Undeclared exception!
      try { 
        helpFormatter0.sort((Iterable<Option>) linkedList0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>();
      Stack<Locale.LanguageRange> stack0 = new Stack<Locale.LanguageRange>();
      Locale locale0 = Locale.TRADITIONAL_CHINESE;
      Set<String> set0 = locale0.getUnicodeLocaleKeys();
      TreeSet<String> treeSet0 = new TreeSet<String>(set0);
      TextStyle textStyle0 = TextStyle.DEFAULT;
      linkedList0.add(textStyle0);
      Locale.FilteringMode locale_FilteringMode0 = Locale.FilteringMode.AUTOSELECT_FILTERING;
      List<String> list0 = Locale.filterTags((List<Locale.LanguageRange>) stack0, (Collection<String>) treeSet0, locale_FilteringMode0);
      ArrayList<List<String>> arrayList0 = new ArrayList<List<String>>();
      HashSet<List<String>> hashSet0 = new HashSet<List<String>>(arrayList0);
      TableDefinition tableDefinition0 = TableDefinition.from("L", linkedList0, list0, hashSet0);
      // Undeclared exception!
      try { 
        helpFormatter0.printOptions(tableDefinition0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      // Undeclared exception!
      try { 
        helpFormatter0.printOptions((Options) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      // Undeclared exception!
      try { 
        helpFormatter0.printOptions((Iterable<Option>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp("E`nAg?9xa!{HgH>cd(", "%s %s", (Options) null, "8T2T@6|$?fM,q^m'Q]", true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      OptionGroup optionGroup0 = new OptionGroup();
      helpFormatter0.toSyntaxOptions(optionGroup0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      Option option0 = new Option("lss2Wu2nOc", false, " | ");
      PriorityQueue<Option> priorityQueue0 = new PriorityQueue<Option>();
      ArrayList<Option> arrayList0 = new ArrayList<Option>(priorityQueue0);
      arrayList0.add(option0);
      Function<Option, OptionGroup> function0 = (Function<Option, OptionGroup>) mock(Function.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(function0).apply(any(org.apache.commons.cli.Option.class));
      String string0 = helpFormatter0.toSyntaxOptions((Iterable<Option>) arrayList0, function0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
      assertEquals("[-lss2Wu2nOc]", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      ArrayList<Option> arrayList0 = new ArrayList<Option>();
      helpFormatter0.sort((Iterable<Option>) arrayList0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      HashSet<Option> hashSet0 = new HashSet<Option>();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp("", "", (Iterable<Option>) hashSet0, "", false);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cmdLineSyntax not provided
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Class<Option> class0 = Option.class;
      ClassLoader classLoader0 = ClassLoader.getSystemClassLoader();
      ServiceLoader<Option> serviceLoader0 = ServiceLoader.load(class0, classLoader0);
      helpFormatter0.toSyntaxOptions((Iterable<Option>) serviceLoader0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      // Undeclared exception!
      try { 
        helpFormatter0.printOptions((TableDefinition) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      List<Option> list0 = helpFormatter0.sort((Iterable<Option>) null);
      HashSet<Option> hashSet0 = new HashSet<Option>(list0);
      helpFormatter0.printOptions((Iterable<Option>) hashSet0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      OptionGroup optionGroup0 = new OptionGroup();
      optionGroup0.setRequired(true);
      Option option0 = new Option((String) null, false, "{l_BgonIc/sq2");
      OptionGroup optionGroup1 = optionGroup0.addOption(option0);
      String string0 = helpFormatter0.toSyntaxOptions(optionGroup1);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      OptionGroup optionGroup0 = new OptionGroup();
      Option option0 = new Option("lss2Wu2nOc", false, " | ");
      PriorityQueue<Option> priorityQueue0 = new PriorityQueue<Option>();
      ArrayList<Option> arrayList0 = new ArrayList<Option>(priorityQueue0);
      arrayList0.add(option0);
      arrayList0.add(option0);
      Function<Option, OptionGroup> function0 = (Function<Option, OptionGroup>) mock(Function.class, new ViolatedAssumptionAnswer());
      doReturn(optionGroup0, optionGroup0).when(function0).apply(any(org.apache.commons.cli.Option.class));
      String string0 = helpFormatter0.toSyntaxOptions((Iterable<Option>) arrayList0, function0);
      assertEquals("", string0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      helpFormatter0.sort((Options) null);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp("org.junitpioneer.jupiter.json.AbstractJsonArgumentsProvider", "org.junitpioneer.jupiter.json.AbstractJsonArgumentsProvider", (Iterable<Option>) null, "org.junitpioneer.jupiter.json.AbstractJsonArgumentsProvider", true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      Collection<Option> collection0 = options0.getOptions();
      LinkedHashSet<Option> linkedHashSet0 = new LinkedHashSet<Option>(collection0);
      helpFormatter0.printHelp("<Ow1n>", "", (Iterable<Option>) linkedHashSet0, "", false);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      OptionFormatter optionFormatter0 = OptionFormatter.from((Option) null);
      OptionFormatter.Builder optionFormatter_Builder0 = new OptionFormatter.Builder(optionFormatter0);
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setOptionFormatBuilder(optionFormatter_Builder0);
      assertSame(helpFormatter_Builder0, helpFormatter_Builder1);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setOptionFormatBuilder((OptionFormatter.Builder) null);
      assertSame(helpFormatter_Builder1, helpFormatter_Builder0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      HelpAppendable helpAppendable0 = helpFormatter0.getHelpAppendable();
      helpFormatter_Builder0.setHelpAppendable(helpAppendable0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setHelpAppendable((HelpAppendable) null);
      assertSame(helpFormatter_Builder1, helpFormatter_Builder0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      String string0 = helpFormatter0.toArgName("");
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
      assertEquals("<>", string0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      String string0 = helpFormatter0.getSyntaxPrefix();
      assertEquals("usage: ", string0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      String string0 = helpFormatter0.getOptionGroupSeparator();
      assertEquals(" | ", string0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      helpFormatter0.getComparator();
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      Options options0 = new Options();
      helpFormatter0.toSyntaxOptions(options0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      options0.addOption((String) null, "huR", true, "The option '%s' was specified but an option from this group has already been selected: '%s'");
      helpFormatter0.printHelp("I1UGr^|\\;6N)", "I1UGr^|\\;6N)", options0, "I1UGr^|\\;6N)", true);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp("", "cmdLineSyntax not provided", options0, "%s %s", false);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cmdLineSyntax not provided
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      helpFormatter0.getSerializer();
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      helpFormatter0.printOptions(options0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      Option option0 = new Option((String) null, false, "3h");
      helpFormatter0.getOptionFormatter(option0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder0);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
      
      helpFormatter0.setSyntaxPrefix("");
      helpFormatter0.getSyntaxPrefix();
      assertEquals("", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      helpFormatter_Builder0.setComparator(helpFormatter0.DEFAULT_COMPARATOR);
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }
}
