/*
 * This file was automatically generated by EvoSuite
 * Tue Nov 11 20:37:49 GMT 2025
 */

package org.apache.commons.cli.help;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.CharArrayWriter;
import java.io.PrintStream;
import java.io.StringWriter;
import java.nio.BufferOverflowException;
import java.nio.ByteBuffer;
import java.nio.CharBuffer;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.PriorityQueue;
import java.util.Queue;
import java.util.ServiceLoader;
import java.util.SortedSet;
import java.util.Stack;
import java.util.TreeSet;
import java.util.Vector;
import java.util.function.Function;
import java.util.function.Predicate;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.example.WeirdOptionFormat;
import org.apache.commons.cli.help.FilterHelpAppendable;
import org.apache.commons.cli.help.TableDefinition;
import org.apache.commons.cli.help.TextHelpAppendable;
import org.apache.commons.cli.help.TextStyle;
import org.apache.commons.text.similarity.LongestCommonSubsequence;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.io.MockFileWriter;
import org.evosuite.runtime.mock.java.io.MockPrintStream;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TextHelpAppendable_ESTest extends TextHelpAppendable_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      TextHelpAppendable.systemOut();
      ArrayList<CharSequence> arrayList0 = new ArrayList<CharSequence>();
      char[] charArray0 = new char[8];
      textHelpAppendable0.setLeftPad((-764));
      charArray0[0] = 'c';
      charArray0[1] = '&';
      charArray0[2] = '';
      charArray0[2] = 's';
      charArray0[4] = 'U';
      charArray0[5] = '(';
      charArray0[6] = 'o';
      charArray0[7] = 'T';
      FileSystemHandling.shouldThrowIOException((EvoSuiteFile) null);
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      arrayList0.add((CharSequence) charBuffer0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendList(true, arrayList0);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.setIndent((-197));
      TextStyle.Builder textStyle_Builder0 = textHelpAppendable0.getTextStyleBuilder();
      ArrayList<Queue<String>> arrayList0 = new ArrayList<Queue<String>>();
      arrayList0.ensureCapacity(30);
      Vector<TextStyle> vector0 = new Vector<TextStyle>();
      textHelpAppendable0.writeColumnQueues(arrayList0, vector0);
      textStyle_Builder0.setLeftPad(74);
      textHelpAppendable0.resize(textStyle_Builder0, 2.0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.printWrapped("K:VCE");
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      char[] charArray0 = new char[8];
      CharBuffer charBuffer0 = CharBuffer.allocate(3556);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) charBuffer0, 1, 3556);
      charBuffer0.rewind();
      CharBuffer charBuffer2 = CharBuffer.wrap((CharSequence) charBuffer1);
      textHelpAppendable0.appendTitle(charBuffer2);
      charArray0[0] = 's';
      charArray0[1] = 'b';
      charArray0[2] = '[';
      charArray0[1] = 'i';
      charArray0[5] = 'b';
      charArray0[0] = '<';
      charBuffer0.duplicate();
      CharBuffer charBuffer3 = CharBuffer.wrap((CharSequence) charBuffer1);
      textHelpAppendable0.appendParagraph(charBuffer3);
      textHelpAppendable0.getIndent();
      TextStyle textStyle0 = TextStyle.DEFAULT;
      // Undeclared exception!
      textHelpAppendable0.makeColumnQueue(charBuffer2, textStyle0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      char[] charArray0 = new char[8];
      CharBuffer charBuffer0 = CharBuffer.allocate(3556);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) charBuffer0, 1, 3556);
      textHelpAppendable0.appendParagraph(charBuffer1);
      charBuffer0.rewind();
      CharBuffer charBuffer2 = CharBuffer.wrap((CharSequence) charBuffer1);
      textHelpAppendable0.appendTitle(charBuffer2);
      charArray0[0] = 's';
      charArray0[1] = 'b';
      charArray0[2] = '[';
      charArray0[4] = 'i';
      charArray0[5] = 'b';
      charArray0[6] = '<';
      charBuffer0.duplicate();
      CharBuffer charBuffer3 = CharBuffer.wrap((CharSequence) charBuffer1);
      // Undeclared exception!
      textHelpAppendable0.appendParagraph(charBuffer3);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      TextHelpAppendable textHelpAppendable1 = TextHelpAppendable.systemOut();
      ArrayList<CharSequence> arrayList0 = new ArrayList<CharSequence>();
      char[] charArray0 = new char[8];
      charArray0[0] = 'c';
      charArray0[1] = '&';
      charArray0[2] = '&';
      charArray0[3] = 's';
      charArray0[4] = 'U';
      charArray0[5] = '(';
      charArray0[6] = 'o';
      charArray0[7] = 'T';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) charBuffer0);
      arrayList0.add((CharSequence) charBuffer1);
      CharBuffer charBuffer2 = CharBuffer.allocate(74);
      arrayList0.add((CharSequence) charBuffer2);
      textHelpAppendable0.appendList(true, arrayList0);
      textHelpAppendable0.getMaxWidth();
      textHelpAppendable0.getMaxWidth();
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textHelpAppendable1.makeColumnQueue(charBuffer1, textStyle0);
      Vector<TextStyle> vector0 = new Vector<TextStyle>();
      // Undeclared exception!
      try { 
        textHelpAppendable0.writeColumnQueues((List<Queue<String>>) null, vector0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      Vector<Option> vector0 = new Vector<Option>(74, 321);
      weirdOptionFormat0.apply((Iterable<Option>) vector0);
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) vector0);
      TableDefinition tableDefinition1 = textHelpAppendable0.adjustTableFormat(tableDefinition0);
      List<TextStyle> list0 = tableDefinition1.columnTextStyles();
      Stack<List<String>> stack0 = new Stack<List<String>>();
      LinkedList<List<String>> linkedList0 = new LinkedList<List<String>>(stack0);
      FileSystemHandling fileSystemHandling0 = new FileSystemHandling();
      ArrayList<String> arrayList0 = new ArrayList<String>();
      arrayList0.add("Error looking up file [%s] with charset [%s].");
      textHelpAppendable0.makeColumnQueues(arrayList0, list0);
      textHelpAppendable0.getLeftPad();
      textHelpAppendable0.adjustTableFormat(tableDefinition0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      TextStyle textStyle0 = TextStyle.DEFAULT;
      ArrayList<String> arrayList0 = new ArrayList<String>();
      arrayList0.add("");
      Vector<TextStyle> vector0 = new Vector<TextStyle>();
      // Undeclared exception!
      try { 
        textHelpAppendable0.makeColumnQueues(arrayList0, vector0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Array index out of range: 0
         //
         verifyException("java.util.Vector", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      Vector<Option> vector0 = new Vector<Option>(74, 321);
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) vector0);
      TableDefinition tableDefinition1 = textHelpAppendable0.adjustTableFormat(tableDefinition0);
      List<TextStyle> list0 = tableDefinition1.columnTextStyles();
      List<String> list1 = tableDefinition1.headers();
      FileSystemHandling fileSystemHandling0 = new FileSystemHandling();
      ArrayList<String> arrayList0 = new ArrayList<String>();
      textHelpAppendable0.makeColumnQueues(arrayList0, list0);
      textHelpAppendable0.getLeftPad();
      textHelpAppendable0.adjustTableFormat(tableDefinition0);
      textHelpAppendable0.makeColumnQueues(list1, list0);
      textHelpAppendable0.adjustTableFormat(tableDefinition1);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      char[] charArray0 = new char[8];
      CharBuffer charBuffer0 = CharBuffer.allocate(3556);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) charBuffer0, 1, 3556);
      charBuffer0.rewind();
      CharBuffer charBuffer2 = CharBuffer.wrap((CharSequence) charBuffer1);
      textHelpAppendable0.appendTitle(charBuffer2);
      charArray0[0] = 's';
      charArray0[1] = 'b';
      charArray0[2] = '[';
      charArray0[3] = 'C';
      charArray0[4] = 'i';
      charArray0[5] = '{';
      charArray0[6] = '<';
      charArray0[7] = 'P';
      CharBuffer charBuffer3 = CharBuffer.wrap(charArray0, 1, 3);
      charBuffer3.duplicate();
      CharBuffer charBuffer4 = CharBuffer.wrap((CharSequence) charBuffer3);
      charBuffer4.read(charBuffer0);
      textHelpAppendable0.appendParagraph(charBuffer4);
      int int0 = new Integer('<');
      TextStyle textStyle0 = TextStyle.DEFAULT;
      // Undeclared exception!
      try { 
        textHelpAppendable0.makeColumnQueue(charBuffer1, textStyle0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      char[] charArray0 = new char[8];
      CharBuffer charBuffer0 = CharBuffer.allocate(3556);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) charBuffer0, 1, 3556);
      charBuffer0.rewind();
      CharBuffer charBuffer2 = CharBuffer.wrap((CharSequence) charBuffer1);
      textHelpAppendable0.appendTitle(charBuffer2);
      charArray0[0] = 's';
      charArray0[1] = 's';
      charArray0[2] = '[';
      charArray0[3] = 'C';
      charArray0[4] = 'i';
      charArray0[5] = 'b';
      charBuffer0.compact();
      charArray0[6] = '<';
      charArray0[7] = 'P';
      CharBuffer charBuffer3 = CharBuffer.wrap(charArray0, 1, 3);
      charBuffer3.duplicate();
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendParagraph(charBuffer1);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      TextHelpAppendable.systemOut();
      ArrayList<CharSequence> arrayList0 = new ArrayList<CharSequence>();
      char[] charArray0 = new char[8];
      charArray0[0] = 'c';
      charArray0[1] = '&';
      charArray0[2] = '&';
      charArray0[3] = 's';
      charArray0[4] = 'U';
      charArray0[5] = '(';
      charArray0[6] = 'o';
      charArray0[7] = 'T';
      CharBuffer charBuffer0 = CharBuffer.allocate(74);
      arrayList0.add((CharSequence) charBuffer0);
      textHelpAppendable0.appendList(true, arrayList0);
      textHelpAppendable0.getMaxWidth();
      textHelpAppendable0.getMaxWidth();
      Vector<TextStyle> vector0 = new Vector<TextStyle>();
      // Undeclared exception!
      try { 
        textHelpAppendable0.writeColumnQueues((List<Queue<String>>) null, vector0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      Vector<Option> vector0 = new Vector<Option>(74, 321);
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) vector0);
      TableDefinition tableDefinition1 = textHelpAppendable0.adjustTableFormat(tableDefinition0);
      List<TextStyle> list0 = tableDefinition1.columnTextStyles();
      List<String> list1 = tableDefinition1.headers();
      Stack<List<String>> stack0 = new Stack<List<String>>();
      LinkedList<List<String>> linkedList0 = new LinkedList<List<String>>(stack0);
      linkedList0.add(list1);
      TableDefinition tableDefinition2 = TableDefinition.from("%s%n", list0, list1, linkedList0);
      textHelpAppendable0.adjustTableFormat(tableDefinition2);
      FileSystemHandling fileSystemHandling0 = new FileSystemHandling();
      TableDefinition.from(" * %s", list0, list1, stack0);
      ArrayList<String> arrayList0 = new ArrayList<String>();
      textHelpAppendable0.makeColumnQueues(arrayList0, list0);
      textHelpAppendable0.getLeftPad();
      textHelpAppendable0.adjustTableFormat(tableDefinition0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      MockPrintStream mockPrintStream0 = new MockPrintStream("5G;Mn.^");
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(mockPrintStream0);
      textHelpAppendable0.appendHeader(3, "5G;Mn.^");
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Object[] objectArray0 = new Object[7];
      objectArray0[0] = (Object) textHelpAppendable0;
      objectArray0[1] = (Object) "";
      objectArray0[2] = (Object) "";
      objectArray0[3] = (Object) textHelpAppendable0;
      Object object0 = new Object();
      objectArray0[4] = object0;
      objectArray0[5] = (Object) "";
      objectArray0[6] = (Object) textHelpAppendable0;
      textHelpAppendable0.appendParagraphFormat("", objectArray0);
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle_Builder0.setLeftPad(74);
      textStyle_Builder0.get();
      FileSystemHandling.appendLineToFile((EvoSuiteFile) null, "C`<X=f)nU /aV,%x");
      ArrayDeque<CharSequence> arrayDeque0 = new ArrayDeque<CharSequence>();
      textHelpAppendable0.appendList(true, arrayDeque0);
      textHelpAppendable0.appendHeader(Integer.MAX_VALUE, "C`<X=f)nU /aV,%x");
      Vector<CharSequence> vector0 = new Vector<CharSequence>();
      textStyle_Builder0.setMinWidth(7);
      textHelpAppendable0.appendList(true, vector0);
      TextStyle.Builder textStyle_Builder1 = textHelpAppendable0.resize(textStyle_Builder0, 1954.878599033321);
      textHelpAppendable0.resize(textStyle_Builder1, (-1180.57993));
      textHelpAppendable0.resize(textStyle_Builder1, (-94.62499276808573));
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      TextStyle textStyle0 = TextStyle.DEFAULT;
      char[] charArray0 = new char[4];
      charArray0[0] = '<';
      charArray0[1] = 'D';
      LongestCommonSubsequence longestCommonSubsequence0 = new LongestCommonSubsequence();
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) charBuffer0);
      longestCommonSubsequence0.longestCommonSubsequence(charBuffer1, charBuffer0);
      textHelpAppendable0.appendHeader(Integer.MAX_VALUE, "<D\u0000\u0000");
      charArray0[2] = ' ';
      charArray0[3] = 'P';
      CharBuffer charBuffer2 = CharBuffer.wrap(charArray0);
      textStyle0.pad(false, charBuffer2);
      textHelpAppendable0.appendTitle("<D P");
      // Undeclared exception!
      try { 
        TextHelpAppendable.indexOfWrap(charBuffer1, 1, (-945));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      byte[] byteArray0 = new byte[1];
      byteArray0[0] = (byte) (-102);
      ByteBuffer.wrap(byteArray0);
      TextStyle.Builder textStyle_Builder0 = textHelpAppendable0.getTextStyleBuilder();
      textStyle_Builder0.setScalable(false);
      TextStyle.Alignment textStyle_Alignment0 = TextStyle.Alignment.CENTER;
      textStyle_Builder0.setScalable(false);
      textStyle_Builder0.setAlignment(textStyle_Alignment0);
      textHelpAppendable0.resize(textStyle_Builder0, 74);
      textHelpAppendable0.getTextStyleBuilder();
      ArrayList<String> arrayList0 = new ArrayList<String>();
      ArrayList<TextStyle> arrayList1 = new ArrayList<TextStyle>();
      arrayList1.add((TextStyle) null);
      textHelpAppendable0.makeColumnQueues(arrayList0, arrayList1);
      TextStyle.Builder textStyle_Builder1 = TextStyle.builder();
      textHelpAppendable0.resize(textStyle_Builder1, (-1.0));
      textHelpAppendable0.setIndent((-3822));
      textHelpAppendable0.getIndent();
      textHelpAppendable0.makeColumnQueues(arrayList0, arrayList1);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      TextStyle.Builder textStyle_Builder0 = textHelpAppendable0.getTextStyleBuilder();
      textHelpAppendable0.resize(textStyle_Builder0, (-752.6384));
      textHelpAppendable0.getMaxWidth();
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      String string0 = "";
      byte[] byteArray0 = new byte[1];
      TextStyle.Builder textStyle_Builder0 = textHelpAppendable0.getTextStyleBuilder();
      textHelpAppendable0.resize(textStyle_Builder0, (byte) (-102));
      byteArray0[0] = (byte) (-102);
      ByteBuffer.wrap(byteArray0);
      TextStyle.Builder textStyle_Builder1 = textHelpAppendable0.getTextStyleBuilder();
      textStyle_Builder1.setScalable(false);
      TextStyle.Alignment textStyle_Alignment0 = TextStyle.Alignment.CENTER;
      textStyle_Builder1.setScalable(false);
      textStyle_Builder1.setAlignment(textStyle_Alignment0);
      // Undeclared exception!
      try { 
        TextHelpAppendable.indexOfWrap("", (-1240), 1);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Width must be greater than 0
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Locale locale0 = Locale.ITALIAN;
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.getMaxWidth();
      Object[] objectArray0 = new Object[2];
      objectArray0[0] = (Object) null;
      objectArray0[1] = (Object) "$yt3&<p";
      TextHelpAppendable textHelpAppendable1 = TextHelpAppendable.systemOut();
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      LinkedHashSet<Option> linkedHashSet0 = new LinkedHashSet<Option>(1);
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) linkedHashSet0);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      Vector<String> vector0 = new Vector<String>();
      HashSet<List<String>> hashSet0 = new HashSet<List<String>>();
      ArrayDeque<List<String>> arrayDeque0 = new ArrayDeque<List<String>>(hashSet0);
      TableDefinition tableDefinition1 = TableDefinition.from((String) null, list0, vector0, arrayDeque0);
      // Undeclared exception!
      try { 
        textHelpAppendable1.adjustTableFormat(tableDefinition1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Array index out of range: 0
         //
         verifyException("java.util.Vector", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.setLeftPad(0);
      StringWriter stringWriter0 = new StringWriter(61);
      StringWriter stringWriter1 = stringWriter0.append('e');
      StringBuffer stringBuffer0 = stringWriter1.getBuffer();
      stringWriter0.flush();
      CharBuffer charBuffer0 = CharBuffer.wrap((CharSequence) stringBuffer0, 0, 0);
      textHelpAppendable0.getMaxWidth();
      TextHelpAppendable.systemOut();
      textHelpAppendable0.setLeftPad(74);
      textHelpAppendable0.setLeftPad(31);
      textHelpAppendable0.getIndent();
      String string0 = "%Qs:VNc~$OM&l";
      textHelpAppendable0.printWrapped("%Qs:VNc~$OM&l");
      textHelpAppendable0.appendHeader(1452, charBuffer0);
      TextHelpAppendable.indexOfWrap(stringBuffer0, Integer.MAX_VALUE, 3);
      Stack<Locale.LanguageRange> stack0 = new Stack<Locale.LanguageRange>();
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      Locale.FilteringMode locale_FilteringMode0 = Locale.FilteringMode.REJECT_EXTENDED_RANGES;
      Locale.filterTags((List<Locale.LanguageRange>) stack0, (Collection<String>) linkedHashSet0, locale_FilteringMode0);
      Vector<TextStyle> vector0 = null;
      try {
        vector0 = new Vector<TextStyle>((-2147483647), 3);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Illegal Capacity: -2147483647
         //
         verifyException("java.util.Vector", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      TextStyle textStyle0 = TextStyle.DEFAULT;
      LongestCommonSubsequence longestCommonSubsequence0 = new LongestCommonSubsequence();
      char[] charArray0 = new char[3];
      charArray0[0] = '=';
      charArray0[1] = ')';
      charArray0[2] = '\'';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      longestCommonSubsequence0.longestCommonSubsequence(charBuffer0, charBuffer0);
      textStyle0.pad(false, "=)'");
      // Undeclared exception!
      try { 
        TextHelpAppendable.indexOfWrap("=)'", 3, (-4007));
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Stack<Queue<String>> stack0 = new Stack<Queue<String>>();
      ArrayDeque<String> arrayDeque0 = new ArrayDeque<String>(1);
      stack0.add((Queue<String>) arrayDeque0);
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>();
      // Undeclared exception!
      try { 
        textHelpAppendable0.writeColumnQueues(stack0, linkedList0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.LinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      TreeSet<CharSequence> treeSet0 = new TreeSet<CharSequence>();
      textHelpAppendable0.appendList(true, treeSet0);
      textHelpAppendable0.getLeftPad();
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      Function.identity();
      LinkedHashSet<Option> linkedHashSet0 = new LinkedHashSet<Option>();
      Integer integer0 = new Integer(0);
      Integer.remainderUnsigned(4232, (-18));
      Vector<TextStyle> vector0 = new Vector<TextStyle>();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) linkedHashSet0);
      List<String> list0 = tableDefinition0.headers();
      LinkedList<List<String>> linkedList0 = new LinkedList<List<String>>();
      PriorityQueue<List<String>> priorityQueue0 = new PriorityQueue<List<String>>(linkedList0);
      TableDefinition tableDefinition1 = TableDefinition.from("", vector0, list0, priorityQueue0);
      TableDefinition tableDefinition2 = textHelpAppendable0.adjustTableFormat(tableDefinition1);
      textHelpAppendable0.adjustTableFormat(tableDefinition2);
      TextHelpAppendable.systemOut();
      Option option0 = mock(Option.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(option0).getDescription();
      doReturn((String) null).when(option0).getLongOpt();
      doReturn((String) null).when(option0).getOpt();
      doReturn((String) null).when(option0).getSince();
      doReturn((Object) null).when(option0).getType();
      doReturn(false).when(option0).hasArg();
      doReturn(false).when(option0).isDeprecated();
      doReturn(false).when(option0).isRequired();
      linkedHashSet0.add(option0);
      linkedHashSet0.remove(integer0);
      TableDefinition tableDefinition3 = weirdOptionFormat0.apply((Iterable<Option>) linkedHashSet0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.adjustTableFormat(tableDefinition3);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      MockFileWriter mockFileWriter0 = new MockFileWriter("g[nGba1");
      mockFileWriter0.getEncoding();
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(mockFileWriter0);
      textHelpAppendable0.appendTitle("g[nGba1");
      textHelpAppendable0.getLeftPad();
      Object[] objectArray0 = new Object[3];
      objectArray0[0] = (Object) "";
      objectArray0[1] = (Object) "";
      objectArray0[2] = (Object) textHelpAppendable0;
      textHelpAppendable0.appendParagraphFormat("", objectArray0);
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textStyle0.pad(true, "g[nGba1");
      textHelpAppendable0.printWrapped("", textStyle0);
      textHelpAppendable0.appendTitle("UTF8");
      textHelpAppendable0.getIndent();
      TextStyle.builder();
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>();
      textStyle0.pad(true, "g[nGba1");
      // Undeclared exception!
      try { 
        textHelpAppendable0.makeColumnQueues((List<String>) null, linkedList0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      char[] charArray0 = new char[8];
      CharBuffer charBuffer0 = CharBuffer.allocate(3556);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) charBuffer0, 1, 3556);
      CharBuffer charBuffer2 = CharBuffer.wrap((CharSequence) charBuffer1);
      textHelpAppendable0.appendTitle(charBuffer2);
      charArray0[0] = 's';
      charArray0[1] = 'b';
      charArray0[2] = '[';
      charArray0[3] = 'C';
      charArray0[4] = 'i';
      charArray0[5] = 'b';
      charArray0[6] = '<';
      charArray0[7] = 'P';
      CharBuffer charBuffer3 = CharBuffer.wrap(charArray0, 1, 3);
      charBuffer3.duplicate();
      CharBuffer charBuffer4 = CharBuffer.wrap((CharSequence) charBuffer3);
      textHelpAppendable0.appendParagraph(charBuffer4);
      textHelpAppendable0.getIndent();
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      String string0 = "a<Q.";
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textStyle0.pad(true, "a<Q.");
      textStyle0.pad(false, "a<Q.");
      textStyle0.toString();
      // Undeclared exception!
      try { 
        textHelpAppendable0.printWrapped("a<Q.", textStyle0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.FilterHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textHelpAppendable0.setMaxWidth((-2807));
      TextStyle textStyle0 = TextStyle.DEFAULT;
      TextStyle.builder();
      textStyle_Builder0.setLeftPad(0);
      textStyle_Builder0.setTextStyle(textStyle0);
      TextStyle.Builder textStyle_Builder1 = textHelpAppendable0.resize(textStyle_Builder0, 0.0);
      textHelpAppendable0.resize(textStyle_Builder1, 1398.43);
      textHelpAppendable0.appendList(false, (Collection<CharSequence>) null);
      textHelpAppendable0.printWrapped("");
      textHelpAppendable0.getTextStyleBuilder();
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      MockPrintStream mockPrintStream0 = new MockPrintStream("=nA1!=dsdOI\"gFUh$<X");
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(mockPrintStream0);
      mockPrintStream0.print((long) 7);
      textHelpAppendable0.getMaxWidth();
      Stack<TextStyle> stack0 = new Stack<TextStyle>();
      TextStyle textStyle0 = TextStyle.DEFAULT;
      stack0.add(textStyle0);
      ArrayList<String> arrayList0 = new ArrayList<String>();
      PriorityQueue<List<String>> priorityQueue0 = new PriorityQueue<List<String>>();
      priorityQueue0.add(arrayList0);
      TableDefinition tableDefinition0 = TableDefinition.from("=nA1!=dsdOI\"gFUh$<X", stack0, arrayList0, priorityQueue0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.adjustTableFormat(tableDefinition0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      TextStyle textStyle0 = TextStyle.DEFAULT;
      TextStyle.builder();
      textStyle0.toString();
      textStyle_Builder0.setLeftPad(7);
      textHelpAppendable0.setLeftPad(0);
      textStyle_Builder0.setLeftPad(1);
      textStyle_Builder0.setScalable(true);
      textStyle_Builder0.setTextStyle(textStyle0);
      TextStyle.builder();
      TextStyle.Builder textStyle_Builder1 = textHelpAppendable0.resize(textStyle_Builder0, 0.0);
      textHelpAppendable0.setLeftPad(Integer.MAX_VALUE);
      TextStyle.Alignment textStyle_Alignment0 = TextStyle.Alignment.LEFT;
      textStyle_Builder1.setAlignment(textStyle_Alignment0);
      textStyle_Builder0.setMinWidth((-665));
      textHelpAppendable0.resize(textStyle_Builder1, (-725.509));
      textHelpAppendable0.setMaxWidth(1214);
      textHelpAppendable0.setLeftPad(0);
      textHelpAppendable0.getLeftPad();
      textHelpAppendable0.getLeftPad();
      textHelpAppendable0.getIndent();
      textHelpAppendable0.makeColumnQueue("TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}", textStyle0);
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      ArrayList<Option> arrayList0 = new ArrayList<Option>();
      HashSet<Option> hashSet0 = new HashSet<Option>();
      arrayList0.addAll((Collection<? extends Option>) hashSet0);
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) arrayList0);
      textHelpAppendable0.appendTable(tableDefinition0);
      Vector<Queue<String>> vector0 = new Vector<Queue<String>>();
      Vector<TextStyle> vector1 = new Vector<TextStyle>();
      textHelpAppendable0.writeColumnQueues(vector0, vector1);
      textHelpAppendable0.getLeftPad();
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      ArrayList<Queue<String>> arrayList0 = new ArrayList<Queue<String>>();
      PriorityQueue<String> priorityQueue0 = new PriorityQueue<String>();
      arrayList0.add((Queue<String>) priorityQueue0);
      Vector<TextStyle> vector0 = new Vector<TextStyle>();
      // Undeclared exception!
      try { 
        textHelpAppendable0.writeColumnQueues(arrayList0, vector0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Array index out of range: 0
         //
         verifyException("java.util.Vector", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      int int0 = 548;
      StringWriter stringWriter0 = new StringWriter(548);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(stringWriter0);
      textHelpAppendable0.appendHeader(548, (CharSequence) null);
      String string0 = "";
      ArrayList<Queue<String>> arrayList0 = new ArrayList<Queue<String>>();
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      LinkedList<Option> linkedList0 = new LinkedList<Option>();
      LinkedList<String> linkedList1 = new LinkedList<String>();
      arrayList0.add((Queue<String>) linkedList1);
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) linkedList0);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      // Undeclared exception!
      try { 
        textHelpAppendable0.writeColumnQueues(arrayList0, list0);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      MockFile mockFile0 = new MockFile("file.encoding");
      MockPrintStream mockPrintStream0 = new MockPrintStream(mockFile0);
      String string0 = "v&AsHsrs~ck";
      Object[] objectArray0 = new Object[5];
      objectArray0[0] = (Object) "v&AsHsrs~ck";
      objectArray0[1] = (Object) "file.encoding";
      objectArray0[2] = (Object) mockPrintStream0;
      objectArray0[3] = (Object) "v&AsHsrs~ck";
      objectArray0[4] = (Object) "file.encoding";
      PrintStream printStream0 = mockPrintStream0.format("v&AsHsrs~ck", objectArray0);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(printStream0);
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textHelpAppendable0.makeColumnQueue("file.encoding", textStyle0);
      int int0 = (-1);
      textHelpAppendable0.setLeftPad((-1));
      textHelpAppendable0.setIndent((-2325));
      TextStyle.Builder textStyle_Builder0 = textHelpAppendable0.getTextStyleBuilder();
      textHelpAppendable0.resize(textStyle_Builder0, 1824.785346);
      ArrayList<Locale.LanguageRange> arrayList0 = new ArrayList<Locale.LanguageRange>();
      HashSet<String> hashSet0 = new HashSet<String>();
      List<String> list0 = Locale.filterTags((List<Locale.LanguageRange>) arrayList0, (Collection<String>) hashSet0);
      ArrayList<TextStyle> arrayList1 = new ArrayList<TextStyle>();
      List<Queue<String>> list1 = textHelpAppendable0.makeColumnQueues(list0, arrayList1);
      // Undeclared exception!
      try { 
        textHelpAppendable0.writeColumnQueues(list1, arrayList1);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      textHelpAppendable0.getLeftPad();
      StringWriter stringWriter0 = new StringWriter();
      char[] charArray0 = new char[7];
      charArray0[0] = 'm';
      charArray0[1] = 'x';
      charArray0[2] = ':';
      charArray0[3] = 'I';
      charArray0[4] = '-';
      charArray0[5] = 'A';
      charArray0[6] = 'j';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0, 0, 1);
      StringWriter stringWriter1 = stringWriter0.append((CharSequence) charBuffer0);
      StringWriter stringWriter2 = stringWriter1.append('x');
      stringWriter2.append((CharSequence) charBuffer0);
      stringWriter1.write((-159));
      StringBuffer stringBuffer0 = stringWriter2.getBuffer();
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendTitle(stringBuffer0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.FilterHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Stack<Queue<String>> stack0 = new Stack<Queue<String>>();
      Vector<TextStyle> vector0 = new Vector<TextStyle>();
      vector0.removeAllElements();
      textHelpAppendable0.writeColumnQueues(stack0, vector0);
      PriorityQueue<CharSequence> priorityQueue0 = new PriorityQueue<CharSequence>();
      char[] charArray0 = new char[8];
      charArray0[0] = 'V';
      charArray0[1] = '?';
      charArray0[2] = 'A';
      charArray0[3] = '?';
      charArray0[4] = '<';
      charArray0[5] = 'p';
      charArray0[6] = 'C';
      charArray0[7] = 'Q';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      priorityQueue0.add(charBuffer0);
      textHelpAppendable0.appendList(false, priorityQueue0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      boolean boolean0 = true;
      String string0 = "";
      textHelpAppendable0.printWrapped("");
      // Undeclared exception!
      try { 
        textHelpAppendable0.adjustTableFormat((TableDefinition) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.getIndent();
      textHelpAppendable0.getTextStyleBuilder();
      CharBuffer charBuffer0 = CharBuffer.allocate(32);
      textHelpAppendable0.appendParagraph(charBuffer0);
      textHelpAppendable0.setLeftPad((-2146));
      textHelpAppendable0.getTextStyleBuilder();
      Stack<Queue<String>> stack0 = new Stack<Queue<String>>();
      ArrayList<TextStyle> arrayList0 = new ArrayList<TextStyle>(0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.writeColumnQueues(stack0, arrayList0);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      StringWriter stringWriter0 = new StringWriter(4049);
      textHelpAppendable0.setIndent(4049);
      StringBuffer stringBuffer0 = stringWriter0.getBuffer();
      FilterHelpAppendable filterHelpAppendable0 = textHelpAppendable0.append((CharSequence) stringBuffer0);
      TextHelpAppendable textHelpAppendable1 = new TextHelpAppendable(filterHelpAppendable0);
      Vector<String> vector0 = new Vector<String>();
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>();
      linkedList0.add((TextStyle) null);
      textHelpAppendable1.appendHeader((-1706), stringBuffer0);
      TextStyle textStyle0 = TextStyle.DEFAULT;
      char[] charArray0 = new char[0];
      CharBuffer charBuffer0 = CharBuffer.allocate(1);
      textStyle0.pad(true, charBuffer0);
      stringWriter0.write(charArray0);
      linkedList0.push(textStyle0);
      textHelpAppendable1.makeColumnQueues(vector0, linkedList0);
      TextHelpAppendable textHelpAppendable2 = TextHelpAppendable.systemOut();
      TextHelpAppendable.indexOfWrap(stringBuffer0, 738, 10);
      textHelpAppendable2.appendParagraph(stringBuffer0);
      textHelpAppendable1.getIndent();
      textHelpAppendable2.setMaxWidth(0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      textHelpAppendable0.setLeftPad(0);
      StringWriter stringWriter0 = new StringWriter(7);
      StringWriter stringWriter1 = stringWriter0.append((CharSequence) null, 0, 0);
      StringWriter stringWriter2 = stringWriter1.append('g');
      StringWriter stringWriter3 = stringWriter2.append((CharSequence) null);
      StringBuffer stringBuffer0 = stringWriter3.getBuffer();
      textHelpAppendable0.setIndent(0);
      stringWriter3.write(0);
      stringWriter3.append((CharSequence) stringBuffer0);
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textHelpAppendable0.makeColumnQueue(stringBuffer0, textStyle0);
      textHelpAppendable0.getMaxWidth();
      textHelpAppendable0.getTextStyleBuilder();
      textHelpAppendable0.appendTitle((CharSequence) null);
      Vector<Queue<String>> vector0 = new Vector<Queue<String>>();
      Stack<TextStyle> stack0 = new Stack<TextStyle>();
      // Undeclared exception!
      try { 
        textHelpAppendable0.writeColumnQueues(vector0, stack0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      String string0 = "";
      linkedList0.add("");
      ArrayList<TextStyle> arrayList0 = new ArrayList<TextStyle>();
      // Undeclared exception!
      try { 
        textHelpAppendable0.makeColumnQueues(linkedList0, arrayList0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendTable((TableDefinition) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      Vector<Option> vector0 = new Vector<Option>(1242, 3652);
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) vector0);
      TableDefinition tableDefinition1 = textHelpAppendable0.adjustTableFormat(tableDefinition0);
      List<TextStyle> list0 = tableDefinition1.columnTextStyles();
      Stack<String> stack0 = new Stack<String>();
      LinkedHashSet<List<String>> linkedHashSet0 = new LinkedHashSet<List<String>>();
      ArrayDeque<List<String>> arrayDeque0 = new ArrayDeque<List<String>>(linkedHashSet0);
      TableDefinition.from("l3*Srl*", list0, stack0, arrayDeque0);
      PriorityQueue<List<String>> priorityQueue0 = new PriorityQueue<List<String>>(3652);
      TableDefinition tableDefinition2 = TableDefinition.from("l3*Srl*", list0, stack0, priorityQueue0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendTable(tableDefinition2);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Array index out of range: 0
         //
         verifyException("java.util.Vector", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      char[] charArray0 = new char[1];
      charArray0[0] = '<';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      charBuffer0.rewind();
      int int0 = 1785;
      TextHelpAppendable.indexOfWrap(charBuffer0, 1785, 10);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(charBuffer0);
      textHelpAppendable0.setMaxWidth(1);
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textStyle_Builder0.setMaxWidth(37);
      textHelpAppendable0.resize(textStyle_Builder0, 1.0);
      TextStyle textStyle0 = TextStyle.DEFAULT;
      // Undeclared exception!
      try { 
        textHelpAppendable0.printWrapped("Width must be greater than 0", textStyle0);
        fail("Expecting exception: BufferOverflowException");
      
      } catch(BufferOverflowException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.CharBuffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      CharArrayWriter charArrayWriter0 = new CharArrayWriter();
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(charArrayWriter0);
      charArrayWriter0.append((CharSequence) "");
      charArrayWriter0.write(631);
      textHelpAppendable0.setIndent(0);
      textHelpAppendable0.printWrapped("");
      textHelpAppendable0.appendTitle("");
      textHelpAppendable0.appendList(true, (Collection<CharSequence>) null);
      textHelpAppendable0.appendParagraph("");
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textHelpAppendable0.makeColumnQueue("", textStyle0);
      Stack<TextStyle> stack0 = new Stack<TextStyle>();
      ArrayList<String> arrayList0 = new ArrayList<String>();
      ArrayDeque<List<String>> arrayDeque0 = new ArrayDeque<List<String>>(3);
      Stack<String> stack1 = new Stack<String>();
      arrayDeque0.add(stack1);
      arrayDeque0.add(arrayList0);
      TableDefinition tableDefinition0 = TableDefinition.from("", stack0, arrayList0, arrayDeque0);
      TableDefinition.from("", stack0, arrayList0, arrayDeque0);
      textHelpAppendable0.appendTable(tableDefinition0);
      TextStyle[] textStyleArray0 = new TextStyle[4];
      textStyleArray0[0] = textStyle0;
      TextStyle textStyle1 = TextStyle.DEFAULT;
      textStyleArray0[1] = textStyle1;
      textStyleArray0[2] = textStyle0;
      textStyleArray0[3] = textStyle0;
      arrayList0.toArray(textStyleArray0);
      textHelpAppendable0.getIndent();
      Stack<TextStyle> stack2 = new Stack<TextStyle>();
      stack2.add(textStyle0);
      textHelpAppendable0.makeColumnQueues(arrayList0, stack2);
      textHelpAppendable0.appendHeader(2599, "");
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      LongestCommonSubsequence longestCommonSubsequence0 = new LongestCommonSubsequence();
      TextStyle textStyle0 = TextStyle.DEFAULT;
      CharBuffer charBuffer0 = CharBuffer.allocate(0);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) charBuffer0);
      textStyle0.pad(false, charBuffer1);
      longestCommonSubsequence0.longestCommonSubsequence("", charBuffer1);
      textHelpAppendable0.appendHeader(136209934, "");
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      Vector<TextStyle> vector0 = new Vector<TextStyle>();
      TreeSet<List<String>> treeSet0 = new TreeSet<List<String>>();
      TableDefinition tableDefinition0 = TableDefinition.from("J)&&E", vector0, (List<String>) null, treeSet0);
      TableDefinition tableDefinition1 = textHelpAppendable0.adjustTableFormat(tableDefinition0);
      textHelpAppendable0.adjustTableFormat(tableDefinition1);
      Class<Option> class0 = Option.class;
      ServiceLoader<Option> serviceLoader0 = ServiceLoader.load(class0);
      TableDefinition tableDefinition2 = weirdOptionFormat0.apply((Iterable<Option>) serviceLoader0);
      textHelpAppendable0.adjustTableFormat(tableDefinition2);
      // Undeclared exception!
      try { 
        TextHelpAppendable.indexOfWrap((CharSequence) null, 7, 7);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      TextStyle textStyle0 = TextStyle.DEFAULT;
      // Undeclared exception!
      try { 
        textHelpAppendable0.makeColumnQueue((CharSequence) null, textStyle0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      TreeSet<CharSequence> treeSet0 = new TreeSet<CharSequence>();
      CharBuffer charBuffer0 = CharBuffer.allocate(6);
      treeSet0.add(charBuffer0);
      textHelpAppendable0.appendList(true, treeSet0);
      TextStyle.Builder textStyle_Builder0 = textHelpAppendable0.getTextStyleBuilder();
      int int0 = 61;
      textHelpAppendable0.resize(textStyle_Builder0, 61);
      char[] charArray0 = new char[5];
      charArray0[0] = '';
      charArray0[1] = '=';
      charArray0[2] = 'E';
      charArray0[3] = '6';
      charArray0[4] = 'z';
      // Undeclared exception!
      try { 
        CharBuffer.wrap(charArray0, 28, 33);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.CharBuffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      TextStyle.Builder textStyle_Builder0 = textHelpAppendable0.getTextStyleBuilder();
      TextStyle.Builder textStyle_Builder1 = textHelpAppendable0.resize(textStyle_Builder0, (-3195.8404));
      textHelpAppendable0.resize(textStyle_Builder1, (-3195.8404));
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      TextHelpAppendable textHelpAppendable1 = new TextHelpAppendable(textHelpAppendable0);
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      TextStyle.Builder textStyle_Builder1 = textHelpAppendable1.resize(textStyle_Builder0, 2725.1311832752363);
      textHelpAppendable0.resize(textStyle_Builder1, 1);
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      TextHelpAppendable.systemOut();
      ArrayList<CharSequence> arrayList0 = new ArrayList<CharSequence>();
      char[] charArray0 = new char[8];
      charArray0[0] = 'c';
      charArray0[1] = '&';
      charArray0[2] = '';
      charArray0[3] = 's';
      charArray0[4] = 'U';
      charArray0[5] = '(';
      charArray0[6] = 'o';
      charArray0[7] = 'T';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      arrayList0.add((CharSequence) charBuffer0);
      textHelpAppendable0.appendList(true, arrayList0);
      textHelpAppendable0.getMaxWidth();
      textHelpAppendable0.getMaxWidth();
      List<Queue<String>> list0 = null;
      Vector<TextStyle> vector0 = new Vector<TextStyle>();
      // Undeclared exception!
      try { 
        vector0.removeElementAt(74);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 74 >= 0
         //
         verifyException("java.util.Vector", e);
      }
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      StringWriter stringWriter0 = new StringWriter();
      StringBuffer stringBuffer0 = stringWriter0.getBuffer();
      textHelpAppendable0.appendParagraph(stringBuffer0);
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      TextHelpAppendable.systemOut();
      CharBuffer charBuffer0 = CharBuffer.allocate(7);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) charBuffer0);
      charBuffer1.clear();
      // Undeclared exception!
      try { 
        TextHelpAppendable.indexOfWrap(charBuffer1, (-2719), 31);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Width must be greater than 0
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      char[] charArray0 = new char[1];
      charArray0[0] = 'K';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      // Undeclared exception!
      try { 
        TextHelpAppendable.indexOfWrap(charBuffer0, 0, 2084);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Width must be greater than 0
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Object[] objectArray0 = new Object[5];
      objectArray0[0] = (Object) textHelpAppendable0;
      objectArray0[1] = (Object) "VF~p old";
      objectArray0[2] = (Object) textHelpAppendable0;
      objectArray0[3] = (Object) "VF~p old";
      objectArray0[4] = (Object) "VF~p old";
      textHelpAppendable0.appendParagraphFormat("VF~p old", objectArray0);
      textHelpAppendable0.getLeftPad();
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      TextHelpAppendable textHelpAppendable1 = TextHelpAppendable.systemOut();
      TreeSet<CharSequence> treeSet0 = new TreeSet<CharSequence>();
      textHelpAppendable1.appendList(true, treeSet0);
      textHelpAppendable0.getMaxWidth();
      textHelpAppendable1.append('D');
      Stack<String> stack0 = new Stack<String>();
      PriorityQueue<TextStyle> priorityQueue0 = new PriorityQueue<TextStyle>();
      ArrayList<TextStyle> arrayList0 = new ArrayList<TextStyle>(priorityQueue0);
      textHelpAppendable1.makeColumnQueues(stack0, arrayList0);
      textHelpAppendable1.printWrapped("/vhm%u|;n[H[E&hi");
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.setLeftPad(1159);
      textHelpAppendable0.setMaxWidth(28);
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textStyle0.pad(true, "{}D];fiD0HXg ");
      textHelpAppendable0.printWrapped(" annotation, but there were ");
      textHelpAppendable0.printWrapped("{}D];fiD0HXg ", textStyle0);
      textHelpAppendable0.getLeftPad();
      textHelpAppendable0.printWrapped("fdw");
      textHelpAppendable0.printWrapped("{}D];fiD0HXg ");
      TextHelpAppendable.indexOfWrap(" annotation, but there were ", 1159, 28);
      textHelpAppendable0.appendTitle("fdw");
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.appendTitle((CharSequence) null);
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textHelpAppendable0.resize(textStyle_Builder0, (-748.05404909021));
      textHelpAppendable0.getMaxWidth();
      // Undeclared exception!
      try { 
        textHelpAppendable0.adjustTableFormat((TableDefinition) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      ArrayList<CharSequence> arrayList0 = new ArrayList<CharSequence>();
      textHelpAppendable0.appendList(true, arrayList0);
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      LinkedList<Queue<String>> linkedList0 = new LinkedList<Queue<String>>();
      ArrayList<TextStyle> arrayList0 = new ArrayList<TextStyle>();
      textHelpAppendable0.writeColumnQueues(linkedList0, arrayList0);
      double double0 = (-1.0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.resize((TextStyle.Builder) null, (-1.0));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      TextHelpAppendable textHelpAppendable1 = TextHelpAppendable.systemOut();
      textHelpAppendable0.setIndent(0);
      Object[] objectArray0 = new Object[6];
      objectArray0[0] = (Object) "";
      objectArray0[1] = (Object) textHelpAppendable1;
      objectArray0[2] = (Object) textHelpAppendable0;
      objectArray0[3] = (Object) textHelpAppendable1;
      Object object0 = new Object();
      objectArray0[4] = object0;
      objectArray0[5] = (Object) "";
      textHelpAppendable0.appendParagraphFormat("", objectArray0);
      textHelpAppendable1.setIndent((-871));
      textHelpAppendable0.setMaxWidth(1);
      // Undeclared exception!
      textHelpAppendable0.printWrapped("=B7Anw^^,{ _");
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      CharBuffer charBuffer0 = CharBuffer.allocate(1);
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textHelpAppendable0.makeColumnQueue(charBuffer0, textStyle0);
      TextStyle.builder();
      textHelpAppendable0.printWrapped("", textStyle0);
      textHelpAppendable0.makeColumnQueue(charBuffer0, textStyle0);
      textHelpAppendable0.setIndent(6);
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textStyle0.toString();
      textStyle0.pad(true, "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}");
      textHelpAppendable0.printWrapped(":BwN$qk2", textStyle0);
      textHelpAppendable0.setMaxWidth(Integer.MAX_VALUE);
      textHelpAppendable0.printWrapped(":BwN$qk2");
      textStyle0.toString();
      Stack<Queue<String>> stack0 = new Stack<Queue<String>>();
      textHelpAppendable0.writeColumnQueues(stack0, (List<TextStyle>) null);
      TextStyle.Builder textStyle_Builder0 = TextStyle.builder();
      textHelpAppendable0.resize(textStyle_Builder0, 0.0);
      TextHelpAppendable.indexOfWrap("TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}", 3, 31);
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      textHelpAppendable0.getTextStyleBuilder();
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      char[] charArray0 = new char[3];
      charArray0[0] = '^';
      charArray0[1] = 'o';
      charArray0[2] = '/';
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      textHelpAppendable0.appendHeader(3314, charBuffer0);
      textHelpAppendable0.appendList(false, (Collection<CharSequence>) null);
      TextHelpAppendable.systemOut();
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      FileSystemHandling.setPermissions((EvoSuiteFile) null, true, false, true);
      FileSystemHandling.setPermissions((EvoSuiteFile) null, true, true, false);
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.getLeftPad();
      FileSystemHandling.appendStringToFile((EvoSuiteFile) null, "Width must be greater than 0");
      TextStyle textStyle0 = TextStyle.DEFAULT;
      TextStyle.builder();
      textHelpAppendable0.printWrapped("Width must be greater than 0", textStyle0);
      LinkedList<CharSequence> linkedList0 = new LinkedList<CharSequence>();
      StringWriter stringWriter0 = new StringWriter(356);
      StringBuffer stringBuffer0 = stringWriter0.getBuffer();
      textHelpAppendable0.appendTitle(stringBuffer0);
      textHelpAppendable0.appendList(false, linkedList0);
      textHelpAppendable0.appendList(true, linkedList0);
      TextHelpAppendable textHelpAppendable1 = TextHelpAppendable.systemOut();
      TextStyle textStyle1 = TextStyle.DEFAULT;
      textHelpAppendable0.makeColumnQueue(stringBuffer0, textStyle1);
      textHelpAppendable0.getLeftPad();
      LongestCommonSubsequence longestCommonSubsequence0 = new LongestCommonSubsequence();
      CharBuffer charBuffer0 = CharBuffer.allocate(1);
      longestCommonSubsequence0.longestCommonSubsequence(stringBuffer0, charBuffer0);
      textHelpAppendable1.makeColumnQueue("", textStyle1);
      textHelpAppendable1.makeColumnQueue("Width must be greater than 0", textStyle1);
      textHelpAppendable1.getMaxWidth();
      HashMap<String, List<String>> hashMap0 = new HashMap<String, List<String>>();
      // Undeclared exception!
      try { 
        Locale.LanguageRange.parse("%s%n", (Map<String, List<String>>) hashMap0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // range=%s%n
         //
         verifyException("java.util.Locale$LanguageRange", e);
      }
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.setLeftPad(0);
      StringWriter stringWriter0 = new StringWriter(61);
      StringWriter stringWriter1 = stringWriter0.append('e');
      StringBuffer stringBuffer0 = stringWriter1.getBuffer();
      stringWriter0.flush();
      CharBuffer charBuffer0 = CharBuffer.wrap((CharSequence) stringBuffer0, 0, 0);
      textHelpAppendable0.getMaxWidth();
      TextHelpAppendable.systemOut();
      textHelpAppendable0.setLeftPad(74);
      textHelpAppendable0.setLeftPad(31);
      textHelpAppendable0.getIndent();
      textHelpAppendable0.printWrapped("%Qs:VNc~$OM&l");
      textHelpAppendable0.appendHeader(1452, charBuffer0);
      TextHelpAppendable.indexOfWrap(stringBuffer0, Integer.MAX_VALUE, 3);
      Stack<Locale.LanguageRange> stack0 = new Stack<Locale.LanguageRange>();
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      Locale.FilteringMode locale_FilteringMode0 = Locale.FilteringMode.REJECT_EXTENDED_RANGES;
      List<String> list0 = Locale.filterTags((List<Locale.LanguageRange>) stack0, (Collection<String>) linkedHashSet0, locale_FilteringMode0);
      Stack<TextStyle> stack1 = new Stack<TextStyle>();
      List<Queue<String>> list1 = textHelpAppendable0.makeColumnQueues(list0, stack1);
      textHelpAppendable0.writeColumnQueues(list1, stack1);
      textHelpAppendable0.printWrapped("%Qs:VNc~$OM&l");
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      HashSet<Option> hashSet0 = new HashSet<Option>();
      TreeSet<Option> treeSet0 = new TreeSet<Option>(hashSet0);
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) treeSet0);
      TableDefinition tableDefinition1 = textHelpAppendable0.adjustTableFormat(tableDefinition0);
      textHelpAppendable0.appendTable(tableDefinition1);
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      FilterHelpAppendable filterHelpAppendable0 = textHelpAppendable0.append((CharSequence) null);
      TextHelpAppendable textHelpAppendable1 = new TextHelpAppendable(filterHelpAppendable0);
      textHelpAppendable0.setMaxWidth(3);
      textHelpAppendable0.setIndent(1);
      TextStyle.Builder textStyle_Builder0 = textHelpAppendable1.getTextStyleBuilder();
      textStyle_Builder0.setIndent(3);
      textHelpAppendable1.resize(textStyle_Builder0, (-923.40678171797));
      FileSystemHandling fileSystemHandling0 = new FileSystemHandling();
      textHelpAppendable1.getLeftPad();
      textHelpAppendable1.getMaxWidth();
      textHelpAppendable0.getMaxWidth();
      Vector<String> vector0 = new Vector<String>();
      vector0.add("visitFileFailedFunction");
      LinkedList<String> linkedList0 = new LinkedList<String>();
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      Vector<Option> vector0 = new Vector<Option>(74, 321);
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) vector0);
      TableDefinition tableDefinition1 = textHelpAppendable0.adjustTableFormat(tableDefinition0);
      List<TextStyle> list0 = tableDefinition1.columnTextStyles();
      List<String> list1 = tableDefinition1.headers();
      LinkedList<List<String>> linkedList0 = new LinkedList<List<String>>();
      TableDefinition.from("%s%n", list0, list1, linkedList0);
      Stack<List<String>> stack0 = new Stack<List<String>>();
      LinkedList<List<String>> linkedList1 = new LinkedList<List<String>>(stack0);
      linkedList1.add(list1);
      linkedList1.add(list1);
      TableDefinition tableDefinition2 = TableDefinition.from("%s%n", list0, list1, linkedList1);
      textHelpAppendable0.adjustTableFormat(tableDefinition2);
      FileSystemHandling fileSystemHandling0 = new FileSystemHandling();
      TableDefinition.from(" * %s", list0, list1, stack0);
      ArrayList<String> arrayList0 = new ArrayList<String>();
      textHelpAppendable0.makeColumnQueues(arrayList0, list0);
      textHelpAppendable0.getLeftPad();
      textHelpAppendable0.adjustTableFormat(tableDefinition0);
      TextHelpAppendable.indexOfWrap("%s%n", 1929, 3);
      textHelpAppendable0.getTextStyleBuilder();
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      TextHelpAppendable.systemOut();
      ArrayList<CharSequence> arrayList0 = new ArrayList<CharSequence>();
      char[] charArray0 = new char[8];
      charArray0[0] = 'q';
      charArray0[1] = '&';
      charArray0[2] = '&';
      charArray0[3] = 's';
      charArray0[4] = 'U';
      charArray0[5] = '(';
      charArray0[6] = 'o';
      charArray0[7] = 'T';
      CharBuffer charBuffer0 = CharBuffer.allocate(74);
      arrayList0.add((CharSequence) charBuffer0);
      textHelpAppendable0.appendList(false, arrayList0);
      textHelpAppendable0.getMaxWidth();
      textHelpAppendable0.getMaxWidth();
      Vector<TextStyle> vector0 = new Vector<TextStyle>();
      // Undeclared exception!
      try { 
        textHelpAppendable0.writeColumnQueues((List<Queue<String>>) null, vector0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.getLeftPad();
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>();
      LinkedList<String> linkedList1 = new LinkedList<String>();
      Predicate<Object> predicate0 = Predicate.isEqual((Object) "org.apache.commons.cli.help.TextHelpAppendable");
      linkedList1.removeIf(predicate0);
      TreeSet<List<String>> treeSet0 = new TreeSet<List<String>>();
      PriorityQueue<List<String>> priorityQueue0 = new PriorityQueue<List<String>>((SortedSet<? extends List<String>>) treeSet0);
      priorityQueue0.add(linkedList1);
      TableDefinition tableDefinition0 = TableDefinition.from("org.apache.commons.cli.help.TextHelpAppendable", linkedList0, linkedList1, priorityQueue0);
      TableDefinition.from(" must be static.", linkedList0, linkedList1, treeSet0);
      textHelpAppendable0.adjustTableFormat(tableDefinition0);
      textHelpAppendable0.setMaxWidth(0);
      TextStyle textStyle0 = TextStyle.DEFAULT;
      textHelpAppendable0.printWrapped(":[7sDeyZ=", textStyle0);
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      LinkedHashSet<Option> linkedHashSet0 = null;
      try {
        linkedHashSet0 = new LinkedHashSet<Option>((Collection<? extends Option>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      Vector<Option> vector0 = new Vector<Option>();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) vector0);
      TableDefinition tableDefinition1 = textHelpAppendable0.adjustTableFormat(tableDefinition0);
      textHelpAppendable0.appendTable(tableDefinition1);
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      assertEquals(74, textHelpAppendable0.getMaxWidth());
      
      char[] charArray0 = new char[8];
      CharBuffer charBuffer0 = CharBuffer.allocate(3556);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) charBuffer0, 1, 3556);
      CharBuffer charBuffer2 = CharBuffer.wrap((CharSequence) charBuffer1);
      textHelpAppendable0.appendTitle(charBuffer2);
      charArray0[1] = 'b';
      charArray0[2] = '[';
      charArray0[5] = '[';
      charArray0[6] = '<';
      charArray0[7] = 'P';
      CharBuffer charBuffer3 = CharBuffer.wrap(charArray0, 1, 3);
      charBuffer3.duplicate();
      CharBuffer charBuffer4 = CharBuffer.wrap((CharSequence) charBuffer3);
      textHelpAppendable0.appendParagraph(charBuffer4);
      int int0 = textHelpAppendable0.getIndent();
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test74()  throws Throwable  {
      MockPrintStream mockPrintStream0 = new MockPrintStream("5G;Mn.^");
      mockPrintStream0.println('v');
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(mockPrintStream0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendHeader((-516), "5G;Mn.^");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // level must be at least 1
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test75()  throws Throwable  {
      // Undeclared exception!
      try { 
        TextHelpAppendable.indexOfWrap(" * %s", (-1971), 2992);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Width must be greater than 0
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test76()  throws Throwable  {
      ArrayList<CharSequence> arrayList0 = new ArrayList<CharSequence>();
      assertTrue(arrayList0.isEmpty());
  }
}
