/*
 * This file was automatically generated by EvoSuite
 * Tue Nov 11 21:05:07 GMT 2025
 */

package org.apache.commons.cli.help;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.CharArrayWriter;
import java.io.StringWriter;
import java.nio.CharBuffer;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.IllegalFormatConversionException;
import java.util.LinkedHashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.PriorityQueue;
import java.util.Stack;
import java.util.UnknownFormatConversionException;
import java.util.Vector;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.example.WeirdOptionFormat;
import org.apache.commons.cli.help.TableDefinition;
import org.apache.commons.cli.help.TextHelpAppendable;
import org.apache.commons.cli.help.TextStyle;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockPrintStream;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HelpAppendable_ESTest extends HelpAppendable_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      Stack<Option> stack0 = new Stack<Option>();
      LinkedList<Option> linkedList0 = new LinkedList<Option>(stack0);
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) linkedList0);
      textHelpAppendable0.appendTable(tableDefinition0);
      assertEquals(3, textHelpAppendable0.getIndent());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.appendParagraph("l-WgDv(nCJ/1`#.IC");
      assertEquals(7, TextHelpAppendable.DEFAULT_LIST_INDENT);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.appendHeader(7, "{^");
      assertEquals(1, textHelpAppendable0.getLeftPad());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      CharBuffer charBuffer0 = CharBuffer.allocate(165);
      textHelpAppendable0.appendTitle(charBuffer0);
      assertEquals(165, charBuffer0.length());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Vector<CharSequence> vector0 = new Vector<CharSequence>(39);
      textHelpAppendable0.appendList(false, vector0);
      assertEquals(74, textHelpAppendable0.getMaxWidth());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendTable((TableDefinition) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CharArrayWriter charArrayWriter0 = new CharArrayWriter(2091);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(charArrayWriter0);
      ArrayList<TextStyle> arrayList0 = new ArrayList<TextStyle>();
      Vector<String> vector0 = new Vector<String>();
      LinkedHashSet<List<String>> linkedHashSet0 = new LinkedHashSet<List<String>>();
      vector0.add("");
      TableDefinition tableDefinition0 = TableDefinition.from("", arrayList0, vector0, linkedHashSet0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendTable(tableDefinition0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      MockPrintStream mockPrintStream0 = new MockPrintStream("`vEX`$O,E");
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(mockPrintStream0);
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      PriorityQueue<Option> priorityQueue0 = new PriorityQueue<Option>();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) priorityQueue0);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      Stack<String> stack0 = new Stack<String>();
      HashSet<List<String>> hashSet0 = new HashSet<List<String>>(3, 1057.6422F);
      TableDefinition tableDefinition1 = TableDefinition.from("A;-=&b!|", list0, stack0, hashSet0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendTable(tableDefinition1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Array index out of range: 0
         //
         verifyException("java.util.Vector", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.setMaxWidth(3547);
      Object[] objectArray0 = new Object[6];
      textHelpAppendable0.printWrapped("ix7C%t");
      textHelpAppendable0.appendParagraphFormat("|5$MoR", objectArray0);
      // Undeclared exception!
      textHelpAppendable0.appendParagraphFormat(";Qhiz<_-L5", objectArray0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Object[] objectArray0 = new Object[2];
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendParagraphFormat("p~a\"g%6${mQpA&#H({", objectArray0);
        fail("Expecting exception: UnknownFormatConversionException");
      
      } catch(UnknownFormatConversionException e) {
         //
         // Conversion = '6'
         //
         verifyException("java.util.Formatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Object[] objectArray0 = new Object[1];
      Object object0 = new Object();
      objectArray0[0] = object0;
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendParagraphFormat("Expected exactly one annotation to provide an ArgumentSource, found %d.", objectArray0);
        fail("Expecting exception: IllegalFormatConversionException");
      
      } catch(IllegalFormatConversionException e) {
         //
         // d != java.lang.Object
         //
         verifyException("java.util.Formatter$FormatSpecifier", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Object[] objectArray0 = new Object[2];
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendParagraphFormat((String) null, objectArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Object[] objectArray0 = new Object[3];
      textHelpAppendable0.setLeftPad((-1));
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendParagraphFormat("canonical-name", objectArray0);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.setMaxWidth((-2));
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendParagraphFormat("@Re eaZ", (Object[]) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Width must be greater than 0
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      StringWriter stringWriter0 = new StringWriter();
      StringBuffer stringBuffer0 = stringWriter0.getBuffer();
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(stringBuffer0);
      textHelpAppendable0.setIndent((-1));
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendParagraph("null");
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      CharArrayWriter charArrayWriter0 = new CharArrayWriter();
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(charArrayWriter0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendHeader(0, "WS*");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // level must be at least 1
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      Object[] objectArray0 = new Object[1];
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendFormat((String) null, objectArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      CharArrayWriter charArrayWriter0 = new CharArrayWriter();
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(charArrayWriter0);
      Object[] objectArray0 = new Object[5];
      textHelpAppendable0.appendFormat("/::UzBFZG", objectArray0);
      assertEquals(1, TextHelpAppendable.DEFAULT_LEFT_PAD);
  }
}
