/*
 * This file was automatically generated by EvoSuite
 * Tue Nov 11 20:59:48 GMT 2025
 */

package org.apache.commons.cli.help;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Collection;
import java.util.PriorityQueue;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.OptionGroup;
import org.apache.commons.cli.help.HelpFormatter;
import org.apache.commons.cli.help.TableDefinition;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HelpFormatter_ESTest extends HelpFormatter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HelpFormatter helpFormatter0 = null;
      try {
        helpFormatter0 = new HelpFormatter((HelpFormatter.Builder) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.AbstractHelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(false);
      HelpFormatter helpFormatter0 = new HelpFormatter(helpFormatter_Builder1);
      PriorityQueue<Option> priorityQueue0 = new PriorityQueue<Option>(helpFormatter0.DEFAULT_COMPARATOR);
      Option option0 = new Option("Options", "^IM#u^0@PsH", false, "usage: ");
      priorityQueue0.add(option0);
      TableDefinition tableDefinition0 = helpFormatter0.getTableDefinition(priorityQueue0);
      assertNotNull(tableDefinition0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      OptionGroup optionGroup1 = optionGroup0.addOption(option0);
      Collection<Option> collection0 = optionGroup1.getOptions();
      TableDefinition tableDefinition0 = helpFormatter0.getTableDefinition(collection0);
      assertNotNull(tableDefinition0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      helpFormatter_Builder0.setShowSince(false);
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      // Undeclared exception!
      try { 
        helpFormatter0.getTableDefinition((Iterable<Option>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.HelpFormatter", e);
      }
  }
}
